<a href="https://www.kaggle.com/code/alawdisoft/arabic-news-classification?scriptVersionId=134253537" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

In [1]:
import numpy as np 
import pandas as pd 

In [2]:
data = pd.read_csv('/kaggle/input/arabic-news-dataset/processed_data.csv')
data

Title  \
0     تيرتل تري لابز للتقنيات الحيويه تحصل علي تمويل...   
1        تعد دراسه الجدوي لمشروعك الناشء 6 عوامل اساسيه   
2     منح جاءزه نوبل الطب لاكتشاف مجال التهاب الكبد ...   
3     هيءه الغذاء والدواء الامريكيه لقاح مودرنا حقق ...   
4     حظر بروتين الجهاز المناعي يساعد علي محاربه عدو...   
...                                                 ...   
8394  قواعد اوروبيه تهدد بخفض 10 ايرادات شركات التكن...   
8395  حوار خاص مهندس سعودي نباتك فكره تهدف لزراعه مل...   
8396                 كريم تطلق خدمه اطلب اي شيء الجديده   
8397  تقرير اممي جديد يشير الي تاثير جاءحه فيروس كور...   
8398  فريق مشترك يتحقق اوضاع النساء والاطفال داخل قو...   

                                                Content  \
0     جاءت جوله التمويل التمهيديه الاولي للشركه بقيا...   
1     تعد دراسه الجدوي متطلبا اساسيا لنجاح اي مشروع ...   
2     وقالت لجنه نوبل للمره الاولي التاريخ يمكن الان...   
3     نشرت الوكاله وثاءق علي الانترنت اعدها موظفوها ...   
4     دراسه حديثه قام فريق العلماء جونز هوبكنز ميديس...   
...                                                 ...   
8394  قالت وكاله بلومبرغ الاثنين ان كبري شركات التكن...   
8395  بدات الفكره نعومه اظفاره عندما كان السابعه عمر...   
8396  اعلنت منصه كريم 4 فبراير الجاري اطلاق خدمه اطل...   
8397  وفقا لتقديرات المكتب الاممي المعني بالمخدرات و...   
8398  تاتي الزياره كجزء تنفيذ اتفاقيه السلام المنشطه...   

                                                   Link         Category  
0     https://ryadiybusiness.com/%d8%aa%d9%8a%d8%b1%...      ريادة أعمال  
1     https://ryadiybusiness.com/%d9%83%d9%8a%d9%81-...      ريادة أعمال  
2     https://arabic.sputniknews.com/science/2020100...  علوم وتكنولوجيا  
3     https://arabic.sputniknews.com/world/202012151...  علوم وتكنولوجيا  
4     https://arabic.rt.com//technology/1161864-%D8%...  علوم وتكنولوجيا  
...                                                 ...              ...  
8394  https://asharq.com/ar/7vNsbHVkd9fTQhBQI70ASx-ق...  علوم وتكنولوجيا  
8395       https://news.un.org/ar/story/2020/09/1062802             أخرى  
8396  https://ryadiybusiness.com/%d9%83%d8%b1%d9%8a%...      ريادة أعمال  
8397       https://news.un.org/ar/story/2020/06/1057232             أخرى  
8398       https://news.un.org/ar/story/2019/11/1043621             أخرى  

[8399 rows x 4 columns]

In [3]:
data['Category'].value_counts()

علوم وتكنولوجيا    2800
أخرى               2800
ريادة أعمال        2799
Name: Category, dtype: int64

In [4]:
data.isnull().sum()

Title        0
Content     13
Link         0
Category     0
dtype: int64

In [5]:
data.dropna(inplace=True)

In [6]:
data['Content']

0       جاءت جوله التمويل التمهيديه الاولي للشركه بقيا...
1       تعد دراسه الجدوي متطلبا اساسيا لنجاح اي مشروع ...
2       وقالت لجنه نوبل للمره الاولي التاريخ يمكن الان...
3       نشرت الوكاله وثاءق علي الانترنت اعدها موظفوها ...
4       دراسه حديثه قام فريق العلماء جونز هوبكنز ميديس...
                              ...                        
8394    قالت وكاله بلومبرغ الاثنين ان كبري شركات التكن...
8395    بدات الفكره نعومه اظفاره عندما كان السابعه عمر...
8396    اعلنت منصه كريم 4 فبراير الجاري اطلاق خدمه اطل...
8397    وفقا لتقديرات المكتب الاممي المعني بالمخدرات و...
8398    تاتي الزياره كجزء تنفيذ اتفاقيه السلام المنشطه...
Name: Content, Length: 8386, dtype: object

In [7]:
data.describe()

Title  \
count                                                8386   
unique                                               7938   
top     صندوق Impact Seed اول صندوق سعودي ينضم لشبكه D...   
freq                                                    4   

                                                  Content  \
count                                                8386   
unique                                               7923   
top     اعلنت منصه GrubTech المتخصصه تطوير انظمه المطا...   
freq                                                    4   

                                                     Link         Category  
count                                                8386             8386  
unique                                               7963                3  
top     https://ryadiybusiness.com/%d9%85%d8%ad%d9%85%...  علوم وتكنولوجيا  
freq                                                    4             2800

In [8]:
x = data['Content']
y = data['Category']
x

0       جاءت جوله التمويل التمهيديه الاولي للشركه بقيا...
1       تعد دراسه الجدوي متطلبا اساسيا لنجاح اي مشروع ...
2       وقالت لجنه نوبل للمره الاولي التاريخ يمكن الان...
3       نشرت الوكاله وثاءق علي الانترنت اعدها موظفوها ...
4       دراسه حديثه قام فريق العلماء جونز هوبكنز ميديس...
                              ...                        
8394    قالت وكاله بلومبرغ الاثنين ان كبري شركات التكن...
8395    بدات الفكره نعومه اظفاره عندما كان السابعه عمر...
8396    اعلنت منصه كريم 4 فبراير الجاري اطلاق خدمه اطل...
8397    وفقا لتقديرات المكتب الاممي المعني بالمخدرات و...
8398    تاتي الزياره كجزء تنفيذ اتفاقيه السلام المنشطه...
Name: Content, Length: 8386, dtype: object

In [9]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=42)

In [10]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()
text_counts = vectorizer.fit_transform(X_train)

In [11]:
text_counts

<5618x139774 sparse matrix of type '<class 'numpy.int64'>'
	with 1205251 stored elements in Compressed Sparse Row format>

In [12]:
from sklearn.feature_extraction.text import TfidfTransformer
tfidf_transformer = TfidfTransformer()

X_train_tfidf = tfidf_transformer.fit_transform(text_counts)
X_train_tfidf.shape


(5618, 139774)

In [13]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()

X_train_tfidf = vectorizer.fit_transform(X_train) # remember to use the original X_train set
X_train_tfidf.shape

(5618, 139774)

In [14]:
from sklearn.svm import LinearSVC
clf = LinearSVC()
clf.fit(X_train_tfidf,y_train)

LinearSVC()

In [15]:
from sklearn.pipeline import Pipeline

text_clf = Pipeline([
    ("tfidf" ,TfidfVectorizer()),
     ('clf', LinearSVC())
])
text_clf.fit(X_train , y_train)

predictions = text_clf.predict(X_test)

In [16]:
from sklearn import metrics
print(metrics.confusion_matrix(y_test,predictions))

[[924   2   5]
 [  2 916  16]
 [  2   9 892]]


In [17]:
print(metrics.classification_report(y_test,predictions)) 

                 precision    recall  f1-score   support

           أخرى       1.00      0.99      0.99       931
    ريادة أعمال       0.99      0.98      0.98       934
علوم وتكنولوجيا       0.98      0.99      0.98       903

       accuracy                           0.99      2768
      macro avg       0.99      0.99      0.99      2768
   weighted avg       0.99      0.99      0.99      2768



In [18]:
print(metrics.accuracy_score(y_test,predictions))

0.9869942196531792
